import {StyleSheet, Dimensions} from 'react-native';

export const loginStyles = StyleSheet.create({
  screen: {
    flex: 1,
    margin: 10,
  },
  button: {
    position: 'absolute',
    bottom: 10,
    flexDirection: 'row',
    marginTop: 1,
    padding: 10,
    paddingHorizontal: 50,
    alignSelf: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    backgroundColor: 'black',
    marginBottom: 15,
    width: '80%',
  },
  textButton: {
    alignSelf: 'center',
    color: 'white',
    fontSize: 20,
    marginHorizontal: 15,
  },
  textButtonResend: {
    alignSelf: 'center',
    color: 'white',
    fontSize: 12,
    marginHorizontal: 15,
  },
  icon: {position: 'absolute', right: 10, top: 8},
  title: {
    color: 'black',
    marginBottom: 20,
    fontSize: 18,
    marginRight: 10,
  },
  flagInputText: {
    color: 'black',
    fontSize: 22,
    backgroundColor: '#f1f1f1',
    borderRadius: 10,
    height: 40,
    marginRight: 50,
    paddingLeft: 8,
  },
  flagStyle: {
    width: 1,
    height: 1,
    borderWidth: 0,
  },
  text: {
    color: 'black',
    margin: 30,
    fontSize: Dimensions.get('window').height < 600 ? 12 : 16,
  },
  inputView: {
    width: '100%',
    alignContent: 'center',
    justifyContent: 'center',
  },
  pickerView: {
    width: '10%',
    alignContent: 'center',
    justifyContent: 'center',
  },
  directionRow: {flexDirection: 'row'},
  viewPhoneInput: {marginLeft: 20},
  buttonConfirm: {
    padding: 5,
    paddingHorizontal: 10,
    borderRadius: 6,
    alignSelf: 'center',
    marginTop: 38,
    width: 190,
    marginBottom: -8,
  },
  buttonConfirmResend: {
    padding: 5,
    paddingHorizontal: 10,
    borderRadius: 6,
    alignSelf: 'center',
    marginTop: 38,
  },
  codeFieldRoot: {marginTop: 20},
  cell: {
    width: 40,
    height: 40,
    lineHeight: 30,
    fontSize: 24,
    borderWidth: 0,
    textAlign: 'center',
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    elevation: 6,
  },
  focusCell: {
    borderColor: '#bb4747',
  },
  nameTextInput: {
    borderRadius: 10,
    marginHorizontal: 10,
    marginBottom: 20,
    backgroundColor: '#f1f1f1',
    height: 50,
    fontSize: 22,
    color: 'black',
    paddingLeft: 10,
  },
  codeContainer: {
    flex: 1,
    margin: 10,
    marginTop: 50,
    marginVertical: 15,
    marginHorizontal: 30,
  },
  wrongCode: {
    color: 'red',
    marginTop: 6,
    marginBottom: -25,
  },
});
