// Generated by https://quicktype.io

export interface CardResponse {
  cards: Card[];
  result_size: number;
}

export interface Card {
  bin: string;
  status: string;
  token: string;
  holder_name: string;
  expiry_year: string;
  expiry_month: string;
  transaction_reference: null | string;
  type: string;
  number: string;
}
