import {Category} from './CategoryResponse.interface';
// Generated by https://quicktype.io

export interface CategoryRecomendedResponse {
  count: number;
  page: number;
  totalPages: number;
  data: Category[];
}
