// Generated by https://quicktype.io

export interface Chat {
  status: boolean;
  reciveNotifications: boolean;
  notificationTokens: string[];
  theme: Theme;
  name: string;
  role: Role;
  createdAt: string;
  updatedAt: string;
  image: Image;
  checkedMessageAt: string;
  email?: string;
  lastUserCheck: string;
  newMessages: NewMessage[];
  id: string;
}

export interface Image {
  url: string;
  id: string;
}

export interface NewMessage {
  id: string;
}

export enum Role {
  ADMIN = 'ADMIN',
  CUN = 'CUN',
  JUN = 'JUN',
}

export enum Theme {
  Default = 'DEFAULT',
}
