// Generated by https://quicktype.io

import {Image} from './Image.interface';

export interface HallResp {
  count: number;
  page: number;
  totalPages: number;
  data: Hall[];
}

export interface Hall {
  status: boolean;
  name: string;
  createdAt: string;
  updatedAt: string;
  image: Image;
  id: string;
}
