// Generated by https://quicktype.io

import {CarItemProps} from './Shop.Interface';
import {Carnet} from './CarnetResponse.interface';
import {STATETRACKCODE} from './Statetrackode.enum';

export interface OrderResponse {
  count: number;
  page: number;
  totalPages: number;
  data: Order[];
}

export interface Order {
  car: CarItemProps[];
  codes: Code[];
  currency: Currency;
  user: string;
  cost: number;
  createdAt: Date;
  updatedAt: Date;
  order: string;
  id: string;
  status: boolean;
  trackcode: Trackcode;
  selectedCarnet: Carnet[];
}

export enum Currency {
  Usd = 'USD',
}

export interface Trackcode {
  state: STATETRACKCODE;
  status: boolean;
  user: string;
  order: string;
  code: string[];
  id: string;
  createdAt: Date;
}
export interface Code {
  category: string;
  code: string;
  id: string;
  ship: string;
}
