import {Category} from './CategoryResponse.interface';
import {Subcategory} from './Subcategory.interface';

export interface CarItemProps {
  category: Category;
  cantidad: number;
}
// Generated by https://quicktype.io

export interface MyShopResponse {
  _id: string;
  car: CarItemProps[];
  user: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface ComboItemProps {
  subcategory: Subcategory;
  cantidad: number;
  node: string;
}
